aa.print("ApplicationConditionDeleteBefore debug");
 
aa.print("PermitId1=" + aa.env.getValue("PermitId1"));
aa.print("PermitId2=" + aa.env.getValue("PermitId2"));
aa.print("PermitId3=" + aa.env.getValue("PermitId3"));
aa.print("CurrentUserID=" + aa.env.getValue("CurrentUserID"));
aa.print("ConditionType=" + aa.env.getValue("ConditionType"));
aa.print("ConditionStatus=" + aa.env.getValue("ConditionStatus"));
aa.print("ConditionSeverity=" + aa.env.getValue("ConditionSeverity"));
aa.print("ConditionId=" + aa.env.getValue("ConditionId"));
aa.print("ConditionExpirationDate=" + aa.env.getValue("ConditionExpirationDate"));
aa.print("ConditionEffectiveDate=" + aa.env.getValue("ConditionEffectiveDate"));
aa.print("ConditionComment=" + aa.env.getValue("ConditionComment"));
aa.print("ConditionApplyDate=" + aa.env.getValue("ConditionApplyDate"));
aa.print("AppliedByStaffMiddleName=" + aa.env.getValue("AppliedByStaffMiddleName"));
aa.print("AppliedByStaffLastName=" + aa.env.getValue("AppliedByStaffLastName"));
aa.print("AppliedByStaffFirstName=" + aa.env.getValue("AppliedByStaffFirstName"));
aa.print("AppliedByDepartmentLevel6=" + aa.env.getValue("AppliedByDepartmentLevel6"));
aa.print("AppliedByDepartmentLevel5=" + aa.env.getValue("AppliedByDepartmentLevel5"));
aa.print("AppliedByDepartmentLevel4=" + aa.env.getValue("AppliedByDepartmentLevel4"));
aa.print("AppliedByDepartmentLevel3=" + aa.env.getValue("AppliedByDepartmentLevel3"));
aa.print("AppliedByDepartmentLevel2=" + aa.env.getValue("AppliedByDepartmentLevel2"));
aa.print("AppliedByDepartmentLevel1=" + aa.env.getValue("AppliedByDepartmentLevel1"));
aa.print("ActionByStaffMiddleName=" + aa.env.getValue("ActionByStaffMiddleName"));
aa.print("ActionByStaffLastName=" + aa.env.getValue("ActionByStaffLastName"));
aa.print("ActionByStaffFirstName=" + aa.env.getValue("ActionByStaffFirstName"));
aa.print("ActionByDepartmentLevel6=" + aa.env.getValue("ActionByDepartmentLevel6"));
aa.print("ActionByDepartmentLevel5=" + aa.env.getValue("ActionByDepartmentLevel5"));
aa.print("ActionByDepartmentLevel4=" + aa.env.getValue("ActionByDepartmentLevel4"));
aa.print("ActionByDepartmentLevel3=" + aa.env.getValue("ActionByDepartmentLevel3"));
aa.print("ActionByDepartmentLevel2=" + aa.env.getValue("ActionByDepartmentLevel2"));
aa.print("ActionByDepartmentLevel1=" + aa.env.getValue("ActionByDepartmentLevel1"));
aa.print("AdditionalInformation=" + aa.env.getValue("AdditionalInformation"));
aa.env.setValue("ScriptReturnCode","0");
aa.env.setValue("ScriptReturnMessage","<ApplicationConditionDelete> <successful>");